"""empty message

Revision ID: 3f77fd06546a
Revises: 
Create Date: 2018-08-12 19:25:57.413101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f77fd06546a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_pair',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('shortened_url', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_pair_shortened_url'), 'url_pair', ['shortened_url'], unique=False)
    op.create_index(op.f('ix_url_pair_timestamp'), 'url_pair', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_pair_timestamp'), table_name='url_pair')
    op.drop_index(op.f('ix_url_pair_shortened_url'), table_name='url_pair')
    op.drop_table('url_pair')
    # ### end Alembic commands ###
